### ISSUE TITLE
Suggestion: Confirm button and preview of code on deactivation page

### ISSUE THREAD

**Issue by KittenOverflow** [LINKIWI/modern-paste#1]
### Case 1:
> A dev on their 20th cup of coffee writing up a 1000 line long paste
> Finally finishes and presses submit
> Wants to copy the deactivation link
> Clicks the link by accident
> All work is lost.

### Case 2:
> Has submitted multiple pastes and saved the deactivation links in a long list
> Wants to deactivate one of the 100 pastes submitted
> Realizes he only has the links and no info on what those point to
> Can't just randomly click links to see which one is the right one

I don't actually know how valid these are, but I can see it being a problem or at least a minor annoyance.

**Comment by LINKIWI** [comment]
This requires some rethinking of UX. I'm thinking the best way to approach this is to scrap the existing deactivation page and instead have the `paste/<paste_id>/deactivate/<deactivation_token>` endpoint also render the paste view page, then present a modal asking for confirmation of deactivation. Then, the paste can be deactivated via AJAX. This is similar to what's already implemented for paste deactivation from the account interface:

![paste-deactivate-account](https://cloud.githubusercontent.com/assets/8386642/12784560/73abe420-ca4d-11e5-9597-5cd8c5cf1aae.png)

This solves case 1 since it requires user confirmation. It also solves case 2 since the user can simply click "cancel" and view the paste as if he/she went to `paste/<paste_id>`.

**Comment by KittenOverflow** [comment]
A solid plan. Keep up the good work!
