### ISSUE TITLE
make is failing

### ISSUE THREAD

**Issue by d2-d2** [LINKIWI/modern-paste#12]
Hello, make command is failing with following message:

```
======================================================================
FAIL: test_version (test_views.test_misc.TestMisc)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/envs/modernpaste/modern-paste/tests/test_views/test_misc.py", line 53, in test_version
    self.assertIn('modern-paste.git', version_string[3])  # You might need to change this if the project is renamed
AssertionError: 'modern-paste.git' not found in 'https://github.com/LINKIWI/modern-paste'

```

Could you please tell me what might be wrong here or is it a bug?

**Comment by LINKIWI** [comment]
This is a known bug. The unit test checks that the `/version` URI correctly prints git details, but will fail if you cloned the repository without the `.git` extension.

A temporary workaround is to change the remote URL to include `modern-paste.git` rather than `modern-paste`. From the repository directory, run

`git remote set-url https://github.com/LINKIWI/modern-paste.git`

Thanks for the report.

**Comment by LINKIWI** [comment]
The unit test will now pass even for different remote URLs.
