### ISSUE TITLE
how to convert time in archive -> posted

### ISSUE THREAD

**Issue by denzfarid** [LINKIWI/modern-paste#34]
hello 
thank you for modern paste :)

i have problem with posted time, in my test time posted have -
this is preview

![Image](http://i.imgur.com/TN8wanU.png)

and in fpaste.org 

![Image](http://i.imgur.com/sD9u6Y6.png)

where can i configure for time posted

thank you

**Comment by LINKIWI** [comment]
When you create a paste, the server automatically assigns it a timestamp: https://github.com/LINKIWI/modern-paste/blob/699b6b42c96243387225e80f809c1619ed6da986/app/models/paste.py#L38

The client-side logic for recent pastes just queries this information from the server and converts the unix timestamp to a relative time: https://github.com/LINKIWI/modern-paste/blob/699b6b42c96243387225e80f809c1619ed6da986/app/static/js/universal/CommonController.js#L18

A discrepancy is usually caused by a bad server time. Is the time zone on the server the same as it is on the client?

**Comment by denzfarid** [comment]
correct! 💯 
duh oh! my bad time in server, my server use UTC 

thank you 🥇

**Comment by LINKIWI** [comment]
You're welcome; glad the issue is resolved.
