### ISSUE TITLE
non-raw urls should support passwords in the url too

### ISSUE THREAD

**Issue by divinity76** [LINKIWI/modern-paste#37]
raw urls support having the password in the url, for example https://demo.modernpaste.com/paste/ejo5DpW974MJp~Bg4S0wzRQDRB9BZ42MRHb4Tt8RGHY=/raw?password=VDiL7sbcVr4vBMEpNWpF

- but non-raw urls, for example, https://demo.modernpaste.com/paste/ejo5DpW974MJp~Bg4S0wzRQDRB9BZ42MRHb4Tt8RGHY=?password=VDiL7sbcVr4vBMEpNWpF

does not. that feels like a weird limitation, and it could come in handy to support it. 

is there any specific reason for not supporting it? and if not, could support be added?

**Comment by LINKIWI** [comment]
Passing a plain-text password as part of a URL is inherently insecure.

The reason that this is explicitly not supported in the non-raw view, or more accurately, *the reason this is **only** supported in the raw view*, is that the raw view does not provide any facilities for the user to securely enter a password. Passing the password in the URL is a bit of a hack for the raw view.

One possible additional feature is supporting passing the password as an HTTP header, rather than as a URL parameter. This can be supported in both the raw and non-raw views.

**Comment by divinity76** [comment]
I don't think it should be an default or encouraged scheme, but I do think that silently supporting it would useful (I know it would be useful for me), but nevermind. As for the "password-in-header" idea, if someone wants to pursue it, I think it deserves it's own issue
